name = "claudometer-api"
main = "src/index.js"
compatibility_date = "2025-07-23"

# Environment variables (you'll need to set these via wrangler secret put)
# REDDIT_CLIENT_ID
# REDDIT_CLIENT_SECRET  
# OPENAI_API_KEY

[vars]
DEV_MODE_ENABLED = "true"  # Set to "true" to enable dev endpoints

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "claudometer-db"
database_id = "a9446fa9-c70d-496f-b9e5-a636e72e8865"

# KV Cache binding
[[kv_namespaces]]
binding = "CLAUDOMETER_CACHE"
id = "237333e4f2b949d69dfc97a42a6fd780"
preview_id = "ba39558f32fe4bcbac01d3bd7859a5ec"

# Cron trigger for hourly data collection
[triggers]
crons = ["0 * * * *"]

# Enable logging for debugging
[observability.logs]
enabled = true