name = "claudometer-api"
main = "src/index.js"
compatibility_date = "2025-07-23"

# Environment variables (you'll need to set these via wrangler secret put)
# REDDIT_CLIENT_ID
# REDDIT_CLIENT_SECRET  
# OPENAI_API_KEY

[vars]
DEV_MODE_ENABLED = "false"  # Set to "true" to enable dev endpoints - MUST BE FALSE IN PRODUCTION

[dev]
port = 8787

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "claudometer-db"
database_id = "a9446fa9-c70d-496f-b9e5-a636e72e8865"

# KV Cache binding
[[kv_namespaces]]
binding = "CLAUDOMETER_CACHE"
id = "237333e4f2b949d69dfc97a42a6fd780"
preview_id = "ba39558f32fe4bcbac01d3bd7859a5ec"

# Cron triggers for multi-platform hourly data collection
# Staggered to avoid Reddit API rate limits and distribute load
[triggers]
crons = [
  "0 * * * *",   # Claude AI - every hour at :00 minutes
  "15 * * * *",  # ChatGPT - every hour at :15 minutes  
  "30 * * * *",  # Google Gemini - every hour at :30 minutes
  "45 * * * *"   # Cache refresh - warm all cache keys at :45 minutes
]

# Enable logging for debugging
[observability.logs]
enabled = true